const caixaPrincipal = document.querySelector('.caixa-principal');
const caixaPerguntas = document.querySelectorAll('.caixa-perguntas');
const caixaAlternativa = document.querySelector('.caixa-alternativa');
const caixaResultado = document.querySelector('.caixa-resultado');
const textoResultado = document.querySelectorAll('.texto-resultado');

const perguntas = [
    {
        enunciado: "Texto01",
        alternativa: [
            "alternativa01",
            "alternativa02"
        ]
    }
]

